config/routes.rb
Rails.application.routes.draw do

  get 'welcome' => 'welcome#index'
  get 'oracle' => 'oracle'
  get 'game' => 'game'
  get 'about' => 'about'

  root 'welcome#index'

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def index
  end
end

app/controllers/oracle_controller.rb
class OracleController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/oracle_helper.rb
module OracleHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/about.html.erb
<h1>About Page</h1>

app/views/game/game.html.erb
<h1>Game Page</h1>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The Chimaera Project by Taverna do Menestrel®
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "CHIMAERA", welcome_path, id: "logo"%>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Play Now", game_path, class: "btn btn-lg btn-primary" %></li>
        <li><%= link_to "Oracle", oracle_path, class: "btn btn-lg btn-primary" %></li>
        <li><%= link_to "About", about_path, class: "btn btn-lg btn-primary" %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chimaera</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/oracle/oracle.html.erb
<h1>Oracle Page</h1>

app/views/welcome/index.html.erb
<h1>Landing Page</h1>